# Use the latest Ubuntu image as the base image
FROM ubuntu:latest

# Update APT package list
RUN apt-get update

# Upgrade currently installed packages
RUN apt-get upgrade -y

# Echo "Hello, World!" to the terminal
CMD echo "Hello, World!"